[analytics]
enabled = false

[features]
daemon_auto_start = false

[sandbox_workspace_write]
network_access = true

[tui]
terminal_title = []
screen_reader_detection_done = true

[mcp_servers.Computer]
command = "computer-use-linux"
args = ["mcp"]

[mcp_servers.Emacs]
command = "/home/rubin/Source/Rubin/scripts/python/emacs-mcp-server.py"

[mcp_servers.Figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.Neovim]
command = "nvim-mcp"

[mcp_servers.Wolfram]
command = "/opt/wolfram/Executables/wolfram"
args = ["-run", 'PacletSymbol["Wolfram/AgentTools","Wolfram`AgentTools`StartMCPServer"][]', "-noinit", "-noprompt"]

[mcp_servers.Wolfram.env]
MCP_SERVER_NAME = "WolframLanguage"
WOLFRAM_BASE = "/usr/share/Wolfram"
WOLFRAM_LOCALBASE = "/home/rubin/.Wolfram/Objects"
WOLFRAM_USERBASE = "/home/rubin/.Wolfram"
