model_provider = "cortecs"

model = "glm-5.3-flash"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_catalog_json = "/home/rubin/.codex/model-catalogs/cortecs.json"

[model_providers.cortecs]
name = "cortecs"
base_url="https://api.cortecs.ai/v1"

[model_providers.cortecs.auth]
command = "tipi.sh"
args = ["cortecs", "default-api-token"]
