model = "qwen/deepseek-v4.1-flash"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_provider = "edenai"
model_catalog_json = "/home/rubin/.codex/model-catalogs/edenai.json"

[model_providers.edenai]
name = "edenai"
base_url="https://api.edenai.run/v3"

[model_providers.edenai.auth]
command = "tipi.sh"
args = ["edenai", "default-api-token"]
