model_provider = "hetzner"

model = "Qwen3.8-27B"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_catalog_json = "/home/rubin/.codex/model-catalogs/hetzner.json"

[model_providers.hetzner]
name = "hetzner"
base_url="https://inference.hetzner.com/api/v1"

[model_providers.hetzner.auth]
command = "tipi.sh"
args = ["hetzner", "default-api-token"]
