model = "glm-5.3"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_provider = "neuralwatt"
model_catalog_json = "/home/rubin/.codex/model-catalogs/neuralwatt.json"

[model_providers.neuralwatt]
name = "neuralwatt"
base_url="https://api.neuralwatt.com/v1"

[model_providers.neuralwatt.auth]
command = "tipi.sh"
args = ["neuralwatt", "default-api-key"]
