model = "muse-spark-1.3"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_provider = "opencode"
model_catalog_json = "/home/rubin/.codex/model-catalogs/opencode.json"

[model_providers.opencode]
name = "opencode"
base_url="https://opencode.ai/zen/v1"

[model_providers.opencode.auth]
command = "tipi.sh"
args = ["opencode", "zen-api-key"]

[projects."/home/rubin/Source/Rubin/dotfiles"]
trust_level = "trusted"
