model_provider = "opencode"

model = "glm-5.3-flash"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_catalog_json = "/home/rubin/.codex/model-catalogs/opencode.json"

[model_providers.opencode]
name = "opencode"
base_url="https://opencode.ai/zen/v1"

[model_providers.opencode.auth]
command = "tipi.sh"
args = ["opencode", "zen-api-key"]
