model = "xiaomi/mimo-v2.6-pro"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_provider = "openrouter"
model_catalog_json = "/home/rubin/.codex/model-catalogs/openrouter.json"

[model_providers.openrouter]
name = "openrouter"
base_url="https://openrouter.ai/api/v1"

[model_providers.openrouter.auth]
command = "tipi.sh"
args = ["openrouter", "rubins-raaf-api-key"]
