model = "z-ai/glm-5.3-flash"
model_reasoning_effort = "max"
plan_mode_reasoning_effort = "max"

model_provider = "orcarouter"
model_catalog_json = "/home/rubin/.codex/model-catalogs/orcarouter.json"

[model_providers.orcarouter]
name = "orcarouter"
base_url="https://api.orcarouter.ai/v1"

[model_providers.orcarouter.auth]
command = "tipi.sh"
args = ["orcarouter", "default-api-token"]

