no-multigrid = true
tabs = false
vsync = true

[box-drawing]
mode = "font-glyph"

[font]
normal = ["PragmataPro"]
size = 11
#hinting = "slight"
#edging = "antialias"

#[font.features]
#"Monospace" = [ "-aalt" ]

