[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[elixir]
source = "github"
github = "elixir-lang/elixir"
use_latest_release = "true"

[intel-gmmlib]
source = "pacman"
pacman = "intel-gmmlib"
strip_release = "true"

[intel-media-driver]
source = "pacman"
pacman = "intel-media-driver"
strip_release = "true"

[openshift-codeready-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/crc/"

[openshift-developer-bin]
source = "regex"
regex = "v\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/odo/"

[openshift-pipelines-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/"

[rcu-bin]
source = "regex"
regex = "d\\d{4}\\.\\d{3}\\([a-z]\\)"
url = "https://files.davisr.me/projects/rcu/download-59ck3sdT/"
