[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[cypher-shell]
source = "regex"
regex = "(\\d+\\.\\d+\\.\\d+) for Developers"
url = "https://neo4j.com/download/"

[infer-bin]
source = "github"
github = "facebook/infer"
use_latest_release = "true"

[intel-gmmlib]
source = "pacman"
pacman = "intel-gmmlib"
strip_release = "true"

[intel-media-driver]
source = "pacman"
pacman = "intel-media-driver"
strip_release = "true"

[jdk17-openj9-bin]
source = "github"
github = "ibmruntimes/semeru17-binaries"
use_latest_release = "true"

[jdk21-openj9-bin]
source = "github"
github = "ibmruntimes/semeru21-binaries"
use_latest_release = "true"

[kotlin-language-server-bin]
source = "github"
github = "fwcd/kotlin-language-server"
use_latest_release = "true"

[lexical-bin]
source = "github"
github = "lexical-lsp/lexical"
use_latest_release = "true"

[moonlight-qt]
source = "github"
github = "moonlight-stream/moonlight-qt"
use_latest_release = "true"

[husky]
source = "github"
github = "typicode/husky"
use_latest_release = "true"

[openshift-codeready-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/crc/"

[openshift-developer-bin]
source = "regex"
regex = "v\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/odo/"

[openshift-pipelines-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/"

[passmark-performancetest-bin]
source = "regex"
regex = ", (v\\d+\\.\\d+ Build \\d+), "
url = "https://www.passmark.com/products/pt_linux/download.php"

[postman2openapi-bin]
source = "github"
github = "kevinswiber/postman2openapi"
use_latest_release = "true"

#[pragmatapro-fonts]
#source = "regex"
#regex = "The actual version is (\\d{1}\\.\\d{3})"
#url = "https://fsd.it/shop/fonts/pragmatapro/"

[pupdate-bin]
source = "github"
github = "mattpannella/pupdate"
use_latest_release = "true"

[rcu-bin]
source = "regex"
regex = "v\\d+\\.\\d+\\.\\d+"
url = "https://files.davisr.me/projects/rcu/download-59ck3sdT/"

[rusty-psn-bin]
source = "github"
github = "RainbowCookie32/rusty-psn"
use_latest_release = "true"

[sbom-tool-bin]
source = "github"
github = "microsoft/sbom-tool"
use_latest_release = "true"

[tidal-dl-ng]
source = "github"
github = "exislow/tidal-dl-ng"
use_latest_release = "true"

[yaml-language-server]
source = "git"
git = "https://github.com/redhat-developer/yaml-language-server.git"
prefix = "v"
