[__config__]
keyfile = "keys.toml"
oldver = "old_ver.json"
newver = "new_ver.json"

[cypher-shell]
source = "regex"
regex = "Neo4j (\\d+\\.\\d+\\.\\d+)"
url = "https://neo4j.com/deployment-center/"

[devproxy-bin]
source = "github"
github = "dotnet/dev-proxy"
use_latest_release = "true"

[gnome-shell-extension-tiling-shell]
source = "github"
github = "domferr/tilingshell"
use_latest_release = "true"

[infer-bin]
source = "github"
github = "facebook/infer"
use_latest_release = "true"

[intel-gmmlib]
source = "pacman"
pacman = "intel-gmmlib"
strip_release = "true"

[intel-media-driver]
source = "pacman"
pacman = "intel-media-driver"
strip_release = "true"

[jdk25-openj9-bin]
source = "github"
github = "ibmruntimes/semeru25-binaries"
use_latest_tag = "true"

[marksman]
source = "github"
github = "artempyanykh/marksman"
use_latest_tag = "true"

[marsdev]
source = "github"
github = "andwn/marsdev"
use_latest_tag = "true"

[moonlight-qt]
source = "github"
github = "moonlight-stream/moonlight-qt"
use_latest_release = "true"

[openshift-codeready-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/crc/"

[openshift-developer-bin]
source = "regex"
regex = "v\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/odo/"

[openshift-pipelines-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/"

[passmark-performancetest-bin]
source = "regex"
regex = ", (v\\d+\\.\\d+ Build \\d+), "
url = "https://www.passmark.com/products/pt_linux/download.php"

#[pragmatapro-fonts]
#source = "regex"
#regex = "The actual version is (\\d{1}\\.\\d{3})"
#url = "https://fsd.it/shop/fonts/pragmatapro/"

[pupdate-bin]
source = "github"
github = "mattpannella/pupdate"
use_latest_release = "true"

[pvsneslib]
source = "github"
github = "alekmaul/pvsneslib"
use_latest_tag = "true"

[rcu-bin]
source = "regex"
regex = "v\\d+\\.\\d+\\.\\d+"
url = "https://files.davisr.me/projects/rcu/download-59ck3sdT/"

[ruby-yard-activesupport-concern]
source = "github"
github = "digitalcuisine/yard-activesupport-concern"
use_latest_tag = "true"

[ruby-yard-solargraph]
source = "github"
github = "castwide/yard-solargraph"
use_latest_tag = "true"

[ruby-solargraph]
source = "github"
github = "castwide/solargraph"
use_latest_tag = "true"

[rusty-psn-bin]
source = "github"
github = "RainbowCookie32/rusty-psn"
use_latest_release = "true"

[sbom-tool-bin]
source = "github"
github = "microsoft/sbom-tool"
use_latest_release = "true"

[scheme-langserver-bin]
source = "github"
github = "ufo5260987423/scheme-langserver"
use_latest_release = "true"

[svelte-language-server]
source = "github"
github = "sveltejs/language-tools"
use_latest_tag = "true"

[tidal-dl-ng]
source = "github"
github = "exislow/tidal-dl-ng"
use_latest_release = "true"

[yaml-language-server]
source = "git"
git = "https://github.com/redhat-developer/yaml-language-server.git"
prefix = "v"
