[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[elixir]
source = "github"
github = "elixir-lang/elixir"
use_latest_release = "true"

[infer-bin]
source = "github"
github = "facebook/infer"
use_latest_release = "true"

[intel-gmmlib]
source = "pacman"
pacman = "intel-gmmlib"
strip_release = "true"

[intel-media-driver]
source = "pacman"
pacman = "intel-media-driver"
strip_release = "true"

[jdk17-graalvm-bin]
source = "regex"
regex = "17\\.\\d+\\.\\d+"
url = "https://www.oracle.com/java/technologies/javase/graalvm-jdk17-archive-downloads.html"

[jdk21-graalvm-bin]
source = "regex"
regex = "21\\.\\d+\\.\\d+"
url = "https://www.oracle.com/java/technologies/javase/graalvm-jdk21-archive-downloads.html"

[jdk17-openj9-bin]
source = "github"
github = "ibmruntimes/semeru17-binaries"
use_latest_release = "true"

[jdk21-openj9-bin]
source = "github"
github = "ibmruntimes/semeru21-binaries"
use_latest_release = "true"

[moonlight-qt]
source = "github"
github = "moonlight-stream/moonlight-qt"
use_latest_release = "true"

[postman2openapi-bin]
source = "github"
github = "kevinswiber/postman2openapi"
use_latest_release = "true"

[pupdate-bin]
source = "github"
github = "mattpannella/pupdate"
use_latest_release = "true"

[rusty-psn-bin]
source = "github"
github = "RainbowCookie32/rusty-psn"
use_latest_release = "true"

[openshift-codeready-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/crc/"

[openshift-developer-bin]
source = "regex"
regex = "v\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/odo/"

[openshift-pipelines-bin]
source = "regex"
regex = "\\d+\\.\\d+\\.\\d+"
url = "https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/"

[pragmatapro-fonts]
source = "regex"
regex = "The actual version is (\\d{1}\\.\\d{3})"
url = "https://fsd.it/shop/fonts/pragmatapro/"

[rcu-bin]
source = "regex"
regex = "d\\d{4}\\.\\d{3}\\([a-z]\\)"
url = "https://files.davisr.me/projects/rcu/download-59ck3sdT/"
