# ~/.bash_aliases: called by .bashrc(1) to add custom aliases.

alias em='em.sh'
alias docker='docker.sh'
alias grep='grep --color=auto'
alias java_home='/usr/libexec/java_home'
alias lein='lein.sh'
alias pforth='pforth -d $HOME/Applications/Forth/pforth28/bin/pforth.dic'
alias pgctl='pgctl.sh'
alias pip='pip-linux.sh'
alias podman='podman.sh'
alias proxy='proxy-mac.sh'
alias rlsqlplus='rlwrap sqlplus'
alias session='$HOME/Syncthing/Source/RAAF/session/session.sh'
alias tipi='tipi.sh'
alias vi='vi.sh'
