set-option -sg escape-time 10

set -g default-shell /bin/bash
set -g extended-keys on
set -g extended-keys-format csi-u
set -g focus-events on
set -g history-limit 10000
set -g mouse on
set -g pane-active-border-style bg=default,fg=color01
set -g pane-border-style fg=color08
set -g set-titles on
set -g set-titles-string '#{pane_title}'
set -g status off

set -sa terminal-features ",alacritty*:ccolour:cstyle:title:RGB:extkeys"
set -ga terminal-overrides ",alacritty*:smcup@:rmcup@"

unbind -n MouseDown3Pane
