#!/bin/bash

bspc config border_width            1
bspc config window_gap              30

bspc config normal_border_color "$(getcolor color0)"
bspc config active_border_color "$(getcolor color0)"
bspc config focused_border_color "$(getcolor color0)"

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc monitor LVDS1 -d 1 2 3 4 5
bspc monitor VGA1 -d  6 7 8 9 0

#"$HOME/.config/bspwm/panel" &

bspc rule -a vncviewer follow=on floating=on
bspc rule -a mplayer follow=on floating=on
bspc rule -a gimp follow=on floating=on

