#!/bin/sh

PANEL_WIDTH=$(xrandr -q | awk -F'current' -F',' 'NR==1 {gsub("( |current)","");print $2}' | cut -dx -f1)
PANEL_GEOMETRY="${PANEL_WIDTH}x14+0+0"
FONT1='-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*'
FONT2='-*-siji-medium-*-*-*-10-*-*-*-*-*-*-*'

getXresColor() {
   echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- | tail -n1)";
}

BACKGROUND_COLOR="#FF333333"
FOREGROUND_COLOR="#FFCCCCCC"

BLACK_COLOR="#FF$(getXresColor color0)"
BLACK2_COLOR="#FF$(getXresColor color8)"
RED_COLOR="#FF$(getXresColor color1)"
RED2_COLOR="#FF$(getXresColor color9)"
GREEN_COLOR="#FF$(getXresColor color2)"
GREEN2_COLOR="#FF$(getXresColor color10)"
YELLOW_COLOR="#FF$(getXresColor color3)"
YELLOW2_COLOR="#FF$(getXresColor color11)"
BLUE_COLOR="#FF$(getXresColor color4)"
BLUE2_COLOR="#FF$(getXresColor color12)"
MAGENTA_COLOR="#FF$(getXresColor color5)"
MAGENTA2_COLOR="#FF$(getXresColor color13)"
CYAN_COLOR="#FF$(getXresColor color6)"
CYAN2_COLOR="#FF$(getXresColor color14)"
WHITE_COLOR="#FF$(getXresColor color7)"
WHITE2_COLOR="#FF$(getXresColor color15)"

BAT_COLOR="#FFCC6666"
WIFI_COLOR="#FFB5BD68"

set | grep _COLOR | grep -v LS_COLORS

SEP=""
