[general]
import = [
    "~/.config/alacritty/dark_theme.toml"
]

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
size = 11

[font.bold]
family = "PragmataPro"
style = "Regular"

[font.bold_italic]
family = "PragmataPro"
style = "Italic"

[font.italic]
family = "PragmataPro"
style = "Italic"

[font.normal]
family = "PragmataPro"
style = "Regular"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dimensions = { columns = 132, lines = 43 }
opacity = 1.0

[terminal]
shell = "/home/rubin/Source/Rubin/scripts/shell/tmux-or-bash.sh"