import = [
    "~/.config/alacritty/themes/themes/github_light.toml"
]

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
size = 10

[font.bold]
family = "monospace"
style = "Regular"

[font.bold_italic]
family = "monospace"
style = "Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
dimensions = { columns = 132, lines = 43 }
