import = [
    "~/.config/alacritty/themes/themes/ayu_light.toml"
]

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
size = 13.0

[font.bold]
family = "monospace"
style = "Regular"

[font.bold_italic]
family = "monospace"
style = "Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
dimensions = { columns = 132, lines = 43 }
