[general]
import = [
    "~/.config/alacritty/themes/themes/hatsunemiku.toml"
]

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
size = 13
offset.y = 1

[font.bold]
family = "Monospace"
style = "Regular"

[font.bold_italic]
family = "Monospace"
style = "Italic"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Regular"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
decorations = "none"
dimensions = { columns = 80, lines = 25 }
opacity = 0.0
